var range_name = {
    0: "臺北/基隆地區",
    1: "桃園地區",
    2: "新竹地區",
    3: "苗栗地區",
    4: "臺中地區",
    5: "彰化地區",
    6: "南投地區",
    7: "雲林地區",
    8: "嘉義地區",
    9: "臺南地區",
    10:"高雄地區",
    11:"屏東地區",
    12:"臺東地區",
    13:"花蓮地區",
    14:"宜蘭地區",
    15:"平溪/深澳線",
    16:"內灣/六家線",
    17:"集集線",
    18:"沙崙線",
};

var train_type_list = {
    "1100": "自強",
    "1101": "自強",
    "1102": "太魯閣",
    "1103": "自強",
    "1104": "自強",
    "1105": "自強",
    "1106": "自強",
    "1107": "普悠瑪",
    "1108": "自強",

    "1110": "莒光",
    "1111": "莒光",
    "1112": "莒光",
    "1113": "莒光",
    "1114": "莒光",
    "1115": "莒光",

    "1120": "復興",
    "1121": "復興",
    "1122": "復興",
    "1130": "電車",
    "1131": "區間",
    "1132": "區間快",
    "1133": "電車",
    "1134": "兩鐵",
    "1135": "區間",
    "1140": "普快車",
    "1141": "柴快車",
    "1150": "柴油車",
    "1151": "普通車",
    "1152": "行包專車",
    "1154": "柴客",
    "1155": "柴客",
    "1270": "普通貨車",
    "1280": "客迴",
    "1281": "柴迴",
    "1282": "臨時客迴",
    "12A0": "調車列車",
    "12A1": "單機迴送",
    "12B0": "試轉運",
    "4200": "特種",
    "5230": "特種"
};
var stop_list = [
{ "range": '0', "stop_id": '1810', "name": '福隆', "name_eng": 'Fulong' },
{ "range": '0', "stop_id": '1809', "name": '貢寮', "name_eng": 'Gongliao' },
{ "range": '0', "stop_id": '1808', "name": '雙溪', "name_eng": 'Shuangxi' },
{ "range": '0', "stop_id": '1807', "name": '牡丹', "name_eng": 'Mudan' },
{ "range": '0', "stop_id": '1806', "name": '三貂嶺', "name_eng": 'Sandiaoling' },
{ "range": '0', "stop_id": '1805', "name": '猴硐', "name_eng": 'Houtong' },
{ "range": '0', "stop_id": '1804', "name": '瑞芳', "name_eng": 'Ruifang' },
{ "range": '0', "stop_id": '1803', "name": '四腳亭', "name_eng": 'Sijiaoting' },
{ "range": '0', "stop_id": '1802', "name": '暖暖', "name_eng": 'Nuannuan' },
{ "range": '0', "stop_id": '1001', "name": '基隆', "name_eng": 'Keelung' },
{ "range": '0', "stop_id": '1029', "name": '三坑', "name_eng": 'Sankeng' },
{ "range": '0', "stop_id": '1002', "name": '八堵', "name_eng": 'Badu' },
{ "range": '0', "stop_id": '1003', "name": '七堵', "name_eng": 'Qidu' },
{ "range": '0', "stop_id": '1030', "name": '百福', "name_eng": 'Baifu' },
{ "range": '0', "stop_id": '1004', "name": '五堵', "name_eng": 'Wudu' },
{ "range": '0', "stop_id": '1005', "name": '汐止', "name_eng": 'Xizhi' },
{ "range": '0', "stop_id": '1031', "name": '汐科', "name_eng": 'Xike' },
{ "range": '0', "stop_id": '1006', "name": '南港', "name_eng": 'Nangang' },
{ "range": '0', "stop_id": '1007', "name": '松山', "name_eng": 'Songshan' },
{ "range": '0', "default_station": true, "stop_id": '1008', "name": '臺北', "name_eng": 'Taipei' },
{ "range": '0', "stop_id": '1009', "name": '萬華', "name_eng": 'Wanhua' },
{ "range": '0', "stop_id": '1011', "name": '板橋', "name_eng": 'Banqiao' },
{ "range": '0', "stop_id": '1032', "name": '浮洲', "name_eng": 'Fuzhou' },
{ "range": '0', "stop_id": '1012', "name": '樹林', "name_eng": 'Shulin' },
{ "range": '0', "stop_id": '1034', "name": '南樹林', "name_eng": 'South Shulin' },
{ "range": '0', "stop_id": '1013', "name": '山佳', "name_eng": 'Shanjia' },
{ "range": '0', "stop_id": '1014', "name": '鶯歌', "name_eng": 'Yingge' },
{ "range": '1', "stop_id": '1015', "default_station": true, "name": '桃園', "name_eng": 'Taoyuan' },
{ "range": '1', "stop_id": '1016', "name": '內壢', "name_eng": 'Neili' },
{ "range": '1', "stop_id": '1017', "name": '中壢', "name_eng": 'Zhongli' },
{ "range": '1', "stop_id": '1018', "name": '埔心', "name_eng": 'Puxin' },
{ "range": '1', "stop_id": '1019', "name": '楊梅', "name_eng": 'Yangmei' },
{ "range": '1', "stop_id": '1020', "name": '富岡', "name_eng": 'Fugang' },
{ "range": '10', "stop_id": '1231', "name": '大湖', "name_eng": 'Dahu' },
{ "range": '10', "stop_id": '1232', "name": '路竹', "name_eng": 'Luzhu' },
{ "range": '10', "stop_id": '1233', "name": '岡山', "name_eng": 'Gangshan' },
{ "range": '10', "stop_id": '1234', "name": '橋頭', "name_eng": 'Qiaotou' },
{ "range": '10', "stop_id": '1235', "name": '楠梓', "name_eng": 'Nanzi' },
{ "range": '10', "stop_id": '1242', "name": '新左營', "name_eng": 'Xinzuoying' },
{ "range": '10', "stop_id": '1236', "name": '左營', "name_eng": 'Zuoying' },
{ "range": '10', "stop_id": '1238', "default_station": true, "name": '高雄', "name_eng": 'Kaohsiung' },
{ "range": '10', "stop_id": '1402', "name": '鳳山', "name_eng": 'Fengshan' },
{ "range": '10', "stop_id": '1403', "name": '後莊', "name_eng": 'Houzhuang' },
{ "range": '10', "stop_id": '1404', "name": '九曲堂', "name_eng": 'Jiuqutang' },
{ "range": '11', "stop_id": '1405', "name": '六塊厝', "name_eng": 'Liukuaicuo' },
{ "range": '11', "stop_id": '1406', "default_station": true, "name": '屏東', "name_eng": 'Pingtung' },
{ "range": '11', "stop_id": '1407', "name": '歸來', "name_eng": 'Guilai' },
{ "range": '11', "stop_id": '1408', "name": '麟洛', "name_eng": 'Linluo' },
{ "range": '11', "stop_id": '1409', "name": '西勢', "name_eng": 'Xishi' },
{ "range": '11', "stop_id": '1410', "name": '竹田', "name_eng": 'Zhutian' },
{ "range": '11', "stop_id": '1411', "name": '潮州', "name_eng": 'Chaozhou' },
{ "range": '11', "stop_id": '1412', "name": '崁頂', "name_eng": 'Kanding' },
{ "range": '11', "stop_id": '1413', "name": '南州', "name_eng": 'Nanzhou' },
{ "range": '11', "stop_id": '1414', "name": '鎮安', "name_eng": 'Zhenan' },
{ "range": '11', "stop_id": '1415', "name": '林邊', "name_eng": 'Linbian' },
{ "range": '11', "stop_id": '1416', "name": '佳冬', "name_eng": 'Jiadong' },
{ "range": '11', "stop_id": '1417', "name": '東海', "name_eng": 'Donghai' },
{ "range": '11', "stop_id": '1418', "name": '枋寮', "name_eng": 'Fangliao' },
{ "range": '11', "stop_id": '1502', "name": '加祿', "name_eng": 'Jialu' },
{ "range": '11', "stop_id": '1503', "name": '內獅', "name_eng": 'Neishi' },
{ "range": '11', "stop_id": '1504', "name": '枋山', "name_eng": 'Fangshan' },
{ "range": '12', "stop_id": '1507', "name": '古莊', "name_eng": 'Guzhuang' },
{ "range": '12', "stop_id": '1508', "name": '大武', "name_eng": 'Dawu' },
{ "range": '12', "stop_id": '1510', "name": '瀧溪', "name_eng": 'Longxi' },
{ "range": '12', "stop_id": '1512', "name": '金崙', "name_eng": 'Jinlun' },
{ "range": '12', "stop_id": '1514', "name": '太麻裡', "name_eng": 'Taimali' },
{ "range": '12', "stop_id": '1516', "name": '知本', "name_eng": 'Zhiben' },
{ "range": '12', "stop_id": '1517', "name": '康樂', "name_eng": 'Kangle' },
{ "range": '12', "stop_id": '1632', "default_station": true, "name": '臺東', "name_eng": 'Taitung' },
{ "range": '12', "stop_id": '1631', "name": '山裡', "name_eng": 'Shanli' },
{ "range": '12', "stop_id": '1630', "name": '鹿野', "name_eng": 'Luye' },
{ "range": '12', "stop_id": '1629', "name": '瑞源', "name_eng": 'Ruiyuan' },
{ "range": '12', "stop_id": '1628', "name": '瑞和', "name_eng": 'Ruihe' },
{ "range": '12', "stop_id": '1626', "name": '關山', "name_eng": 'Guanshan' },
{ "range": '12', "stop_id": '1625', "name": '海端', "name_eng": 'Haiduan' },
{ "range": '12', "stop_id": '1624', "name": '池上', "name_eng": 'Chishang' },
{ "range": '13', "stop_id": '1623', "name": '富裡', "name_eng": 'Fuli' },
{ "range": '13', "stop_id": '1622', "name": '東竹', "name_eng": 'Dongzhu' },
{ "range": '13', "stop_id": '1621', "name": '東里', "name_eng": 'Dongli' },
{ "range": '13', "stop_id": '1619', "name": '玉裡', "name_eng": 'Yuli' },
{ "range": '13', "stop_id": '1617', "name": '三民', "name_eng": 'Sanmin' },
{ "range": '13', "stop_id": '1616', "name": '瑞穗', "name_eng": 'Ruisui' },
{ "range": '13', "stop_id": '1614', "name": '富源', "name_eng": 'Fuyuan' },
{ "range": '13', "stop_id": '1613', "name": '大富', "name_eng": 'Dafu' },
{ "range": '13', "stop_id": '1612', "name": '光復', "name_eng": 'Guangfu' },
{ "range": '13', "stop_id": '1611', "name": '萬榮', "name_eng": 'Wanrong' },
{ "range": '13', "stop_id": '1610', "name": '鳳林', "name_eng": 'Fenglin' },
{ "range": '13', "stop_id": '1609', "name": '南平', "name_eng": 'Nanping' },
{ "range": '13', "stop_id": '1607', "name": '豐田', "name_eng": 'Fengtian' },
{ "range": '13', "stop_id": '1606', "name": '壽豐', "name_eng": 'Shoufeng' },
{ "range": '13', "stop_id": '1605', "name": '平和', "name_eng": 'Pinghe' },
{ "range": '13', "stop_id": '1604', "name": '志學', "name_eng": 'Zhixue' },
{ "range": '13', "stop_id": '1602', "name": '吉安', "name_eng": 'Jian' },
{ "range": '13', "stop_id": '1715', "default_station": true, "name": '花蓮', "name_eng": 'Hualien' },
{ "range": '13', "stop_id": '1714', "name": '北埔', "name_eng": 'Beipu' },
{ "range": '13', "stop_id": '1713', "name": '景美', "name_eng": 'Jingmei' },
{ "range": '13', "stop_id": '1712', "name": '新城', "name_eng": 'Xincheng' },
{ "range": '13', "stop_id": '1711', "name": '崇德', "name_eng": 'Chongde' },
{ "range": '13', "stop_id": '1710', "name": '和仁', "name_eng": 'Heren' },
{ "range": '13', "stop_id": '1709', "name": '和平', "name_eng": 'Heping' },
{ "range": '14', "stop_id": '1708', "name": '漢本', "name_eng": 'Hanben' },
{ "range": '14', "stop_id": '1706', "name": '武塔', "name_eng": 'Wuta' },
{ "range": '14', "stop_id": '1705', "name": '南澳', "name_eng": 'Nanao' },
{ "range": '14', "stop_id": '1704', "name": '東澳', "name_eng": 'Dongao' },
{ "range": '14', "stop_id": '1703', "name": '永樂', "name_eng": 'Yongle' },
{ "range": '14', "stop_id": '1827', "name": '蘇澳', "name_eng": 'Suao' },
{ "range": '14', "stop_id": '1826', "name": '蘇澳新', "name_eng": 'Suaoxin' },
{ "range": '14', "stop_id": '1825', "name": '新馬', "name_eng": 'Xinma' },
{ "range": '14', "stop_id": '1824', "name": '冬山', "name_eng": 'Dongshan' },
{ "range": '14', "stop_id": '1823', "name": '羅東', "name_eng": 'Luodong' },
{ "range": '14', "stop_id": '1822', "name": '中裡', "name_eng": 'Zhongli' },
{ "range": '14', "stop_id": '1821', "name": '二結', "name_eng": 'Erjie' },
{ "range": '14', "stop_id": '1820', "default_station": true, "name": '宜蘭', "name_eng": 'Yilan' },
{ "range": '14', "stop_id": '1819', "name": '四城', "name_eng": 'Sicheng' },
{ "range": '14', "stop_id": '1818', "name": '礁溪', "name_eng": 'Jiaoxi' },
{ "range": '14', "stop_id": '1817', "name": '頂埔', "name_eng": 'Dingpu' },
{ "range": '14', "stop_id": '1816', "name": '頭城', "name_eng": 'Toucheng' },
{ "range": '14', "stop_id": '1815', "name": '外澳', "name_eng": 'Waiao' },
{ "range": '14', "stop_id": '1814', "name": '龜山', "name_eng": 'Guishan' },
{ "range": '14', "stop_id": '1813', "name": '大溪', "name_eng": 'Daxi' },
{ "range": '14', "stop_id": '1812', "name": '大裡', "name_eng": 'Dali' },
{ "range": '14', "stop_id": '1811', "name": '石城', "name_eng": 'Shicheng' },
{ "range": '15', "stop_id": '1908', "name": '菁桐', "name_eng": 'Jingtong' },
{ "range": '15', "stop_id": '1907', "default_station": true, "name": '平溪', "name_eng": 'Pingxi' },
{ "range": '15', "stop_id": '1906', "name": '嶺腳', "name_eng": 'Lingjiao' },
{ "range": '15', "stop_id": '1905', "name": '望古', "name_eng": 'Wanggu' },
{ "range": '15', "stop_id": '1904', "name": '十分', "name_eng": 'Shifen' },
{ "range": '15', "stop_id": '1903', "name": '大華', "name_eng": 'Dahua' },
{ "range": '15', "stop_id": '1806', "name": '三貂嶺', "name_eng": 'Sandiaoling' }, //add
{ "range": '15', "stop_id": '6103', "name": '海科館', "name_eng": 'NMMST' },
{ "range": '16', "stop_id": '1025', "name": '新竹', "name_eng": 'Hsinchu' }, // add
{ "range": '16', "stop_id": '1024', "name": '北新竹', "name_eng": 'North Hsinchu' }, // add
{ "range": '16', "stop_id": '2212', "name": '千甲', "name_eng": 'Qianjia' },
{ "range": '16', "stop_id": '2213', "name": '新莊', "name_eng": 'Xinzhuang' },
{ "range": '16', "stop_id": '2203', "name": '竹中', "name_eng": 'Zhuzhong' },
{ "range": '16', "stop_id": '2214', "name": '六家', "name_eng": 'Liujia' },
{ "range": '16', "stop_id": '2204', "name": '上員', "name_eng": 'Shangyuan' },
{ "range": '16', "stop_id": '2211', "name": '榮華', "name_eng": 'Ronghua' },
{ "range": '16', "stop_id": '2205', "name": '竹東', "name_eng": 'Zhudong' },
{ "range": '16', "stop_id": '2206', "name": '橫山', "name_eng": 'Hengshan' },
{ "range": '16', "stop_id": '2207', "name": '九讚頭', "name_eng": 'Jiuzantou' },
{ "range": '16', "stop_id": '2208', "name": '合興', "name_eng": 'Hexing' },
{ "range": '16', "stop_id": '2209', "name": '富貴', "name_eng": 'Fugui' },
{ "range": '16', "stop_id": '2210', "default_station": true, "name": '內灣', "name_eng": 'Neiwan' },
{ "range": '17', "stop_id": '1207', "name": '二水', "name_eng": 'Ershui' }, // add
{ "range": '17', "stop_id": '2702', "name": '源泉', "name_eng": 'Yuanquan' },
{ "range": '17', "stop_id": '2703', "name": '濁水', "name_eng": 'Zhuoshui' },
{ "range": '17', "stop_id": '2704', "name": '龍泉', "name_eng": 'Longquan' },
{ "range": '17', "stop_id": '2705', "default_station": true, "name": '集集', "name_eng": 'Jiji' },
{ "range": '17', "stop_id": '2706', "name": '水裡', "name_eng": 'Shuili' },
{ "range": '17', "stop_id": '2707', "name": '車埕', "name_eng": 'Checheng' },
{ "range": '18', "stop_id": '5101', "name": '長榮大學', "name_eng": 'Chang Jung Christian University' },
{ "range": '18', "stop_id": '5102', "default_station": true, "name": '沙崙', "name_eng": 'Shalun' },
{ "range": '2', "stop_id": '1033', "name": '北湖', "name_eng": 'Beihu(China University of Technology)' },
{ "range": '2', "stop_id": '1021', "name": '湖口', "name_eng": 'Hukou' },
{ "range": '2', "stop_id": '1022', "name": '新豐', "name_eng": 'Xinfeng' },
{ "range": '2', "stop_id": '1023', "name": '竹北', "name_eng": 'Zhubei' },
{ "range": '2', "stop_id": '1024', "name": '北新竹', "name_eng": 'North Hsinchu' },
{ "range": '2', "stop_id": '1025', "default_station": true, "name": '新竹', "name_eng": 'Hsinchu' },
{ "range": '2', "stop_id": '1035', "name": '三姓橋', "name_eng": 'Sanxingqiao' },
{ "range": '2', "stop_id": '1026', "name": '香山', "name_eng": 'Xiangshan' },
{ "range": '3', "stop_id": '1027', "name": '崎頂', "name_eng": 'Qiding' },
{ "range": '3', "stop_id": '1028', "name": '竹南', "name_eng": 'Zhunan' },
{ "range": '3', "stop_id": '1102', "name": '談文', "name_eng": 'Tanwen' },
{ "range": '3', "stop_id": '1104', "name": '大山', "name_eng": 'Dashan' },
{ "range": '3', "stop_id": '1105', "name": '後龍', "name_eng": 'Houlong' },
{ "range": '3', "stop_id": '1106', "name": '龍港', "name_eng": 'Longgang' },
{ "range": '3', "stop_id": '1107', "name": '白沙屯', "name_eng": 'Baishatun' },
{ "range": '3', "stop_id": '1108', "name": '新埔', "name_eng": 'Xinpu' },
{ "range": '3', "stop_id": '1109', "name": '通霄', "name_eng": 'Tongxiao' },
{ "range": '3', "stop_id": '1110', "name": '苑裡', "name_eng": 'Yuanli' },
{ "range": '3', "stop_id": '1302', "name": '造橋', "name_eng": 'Zaoqiao' },
{ "range": '3', "stop_id": '1304', "name": '豐富', "name_eng": 'Fengfu' },
{ "range": '3', "stop_id": '1305', "default_station": true, "name": '苗栗', "name_eng": 'Miaoli' },
{ "range": '3', "stop_id": '1307', "name": '南勢', "name_eng": 'Nanshi' },
{ "range": '3', "stop_id": '1308', "name": '銅鑼', "name_eng": 'Tongluo' },
{ "range": '3', "stop_id": '1310', "name": '三義', "name_eng": 'Sanyi' },
{ "range": '4', "stop_id": '1111', "name": '日南', "name_eng": 'Rinan' },
{ "range": '4', "stop_id": '1112', "name": '大甲', "name_eng": 'Dajia' },
{ "range": '4', "stop_id": '1113', "name": '臺中港', "name_eng": 'Taichung Port' },
{ "range": '4', "stop_id": '1114', "name": '清水', "name_eng": 'Qingshui' },
{ "range": '4', "stop_id": '1115', "name": '沙鹿', "name_eng": 'Shalu' },
{ "range": '4', "stop_id": '1116', "name": '龍井', "name_eng": 'Longjing' },
{ "range": '4', "stop_id": '1117', "name": '大肚', "name_eng": 'Dadu' },
{ "range": '4', "stop_id": '1118', "name": '追分', "name_eng": 'Zhuifen' },
{ "range": '4', "stop_id": '1314', "name": '泰安', "name_eng": 'Taian' },
{ "range": '4', "stop_id": '1315', "name": '後裡', "name_eng": 'Houli' },
{ "range": '4', "stop_id": '1317', "name": '豐原', "name_eng": 'Fengyuan' },
{ "range": '4', "stop_id": '1318', "name": '潭子', "name_eng": 'Tanzi' },
{ "range": '4', "stop_id": '1323', "name": '太原', "name_eng": 'Taiyuan' },
{ "range": '4', "stop_id": '1319', "default_station": true, "name": '臺中', "name_eng": 'Taichung' },
{ "range": '4', "stop_id": '1322', "name": '大慶', "name_eng": 'Daqing' },
{ "range": '4', "stop_id": '1320', "name": '烏日', "name_eng": 'Wuri' },
{ "range": '4', "stop_id": '1324', "name": '新烏日', "name_eng": 'Xinwuri' },
{ "range": '4', "stop_id": '1321', "name": '成功', "name_eng": 'Chenggong' },
{ "range": '5', "stop_id": '1120', "default_station": true, "name": '彰化', "name_eng": 'Changhua' },
{ "range": '5', "stop_id": '1202', "name": '花壇', "name_eng": 'Huatan' },
{ "range": '5', "stop_id": '1240', "name": '大村', "name_eng": 'Dacun' },
{ "range": '5', "stop_id": '1203', "name": '員林', "name_eng": 'Yuanlin' },
{ "range": '5', "stop_id": '1204', "name": '永靖', "name_eng": 'Yongjing' },
{ "range": '5', "stop_id": '1205', "name": '社頭', "name_eng": 'Shetou' },
{ "range": '5', "stop_id": '1206', "name": '田中', "name_eng": 'Tianzhong' },
{ "range": '5', "stop_id": '1207', "name": '二水', "name_eng": 'Ershui' },
{ "range": '6', "stop_id": '2702', "name": '源泉', "name_eng": 'Yuanquan' }, // add
{ "range": '6', "stop_id": '2703', "name": '濁水', "name_eng": 'Zhuoshui' }, // add
{ "range": '6', "stop_id": '2704', "name": '龍泉', "name_eng": 'Longquan' }, // add
{ "range": '6', "stop_id": '2705', "default_station": true, "name": '集集', "name_eng": 'Jiji' },
{ "range": '6', "stop_id": '2706', "name": '水裡', "name_eng": 'Shuili' }, // add
{ "range": '6', "stop_id": '2707', "name": '車埕', "name_eng": 'Checheng' }, // add
{ "range": '7', "stop_id": '1208', "name": '林內', "name_eng": 'Linnei' },
{ "range": '7', "stop_id": '1209', "name": '石榴', "name_eng": 'Shiliu' },
{ "range": '7', "stop_id": '1210', "default_station": true, "name": '斗六', "name_eng": 'Douliu' },
{ "range": '7', "stop_id": '1211', "name": '斗南', "name_eng": 'Dounan' },
{ "range": '7', "stop_id": '1212', "name": '石龜', "name_eng": 'Shigui' },
{ "range": '8', "stop_id": '1213', "name": '大林', "name_eng": 'Dalin' },
{ "range": '8', "stop_id": '1214', "name": '民雄', "name_eng": 'Minxiong' },
{ "range": '8', "stop_id": '1241', "name": '嘉北', "name_eng": 'Jiabei' },
{ "range": '8', "stop_id": '1215', "default_station": true, "name": '嘉義', "name_eng": 'Chiayi' },
{ "range": '8', "stop_id": '1217', "name": '水上', "name_eng": 'Shuishang' },
{ "range": '8', "stop_id": '1218', "name": '南靖', "name_eng": 'Nanjing' },
{ "range": '9', "stop_id": '1219', "name": '後壁', "name_eng": 'Houbi' },
{ "range": '9', "stop_id": '1220', "name": '新營', "name_eng": 'Xinying' },
{ "range": '9', "stop_id": '1221', "name": '柳營', "name_eng": 'Liuying' },
{ "range": '9', "stop_id": '1222', "name": '林鳳營', "name_eng": 'Linfengying' },
{ "range": '9', "stop_id": '1223', "name": '隆田', "name_eng": 'Longtian' },
{ "range": '9', "stop_id": '1224', "name": '拔林', "name_eng": 'Balin' },
{ "range": '9', "stop_id": '1225', "name": '善化', "name_eng": 'Shanhua' },
{ "range": '9', "stop_id": '1244', "name": '南科', "name_eng": 'Nanke' },
{ "range": '9', "stop_id": '1226', "name": '新市', "name_eng": 'Xinshi' },
{ "range": '9', "stop_id": '1227', "name": '永康', "name_eng": 'Yongkang' },
{ "range": '9', "stop_id": '1239', "name": '大橋', "name_eng": 'Daqiao' },
{ "range": '9', "stop_id": '1228', "default_station": true, "name": '臺南', "name_eng": 'Tainan' },
{ "range": '9', "stop_id": '1229', "name": '保安', "name_eng": 'Baoan' },
{ "range": '9', "stop_id": '1243', "name": '仁德', "name_eng": 'Rende' },
{ "range": '9', "stop_id": '1230', "name": '中洲', "name_eng": 'Zhongzhou' },
{ "range": '9', "stop_id": '5101', "name": '長榮大學', "name_eng": 'Chang Jung Christian University' }, // add
{ "range": '9', "stop_id": '5102', "name": '沙崙', "name_eng": 'Shalun' } // add
];


// range -> stops table
var train_range = [];
train_range[-1] = {
    id: -1,
    name: "選擇地區",
    stops: [{
        StationName: {Zh_tw: "--", en: "--"},
        StationId: -1
    }]
};

for (var i in range_name) {
    train_range[i] = {
        id: i,
        name: range_name[i],
        stops: []
    }
}

// stop range mapping table
var range_table = [];
for (var i in stop_list) {
    var stop = stop_list[i];
    if (stop.default_station === true)
        train_range[stop.range].default_value = stop.stop_id;

    if (!(stop.stop_id in range_table))
       range_table[stop.stop_id] = [];

    range_table[stop.stop_id].push(stop.range);
}

